### PR TITLE
Peng 9789

### PR DESCRIPTION
**Pull request by CodingKayla**

### CODE REVIEW

**Comment by zambien** [comment]
@CodingKayla Do you think any updates to the examples in the README should be done here?  I try to keep examples there for many of the resources which are available.  I realize all resources aren't documented there but thought to ask.

Thanks!

**Comment by zambien** [comment]
Merging as folks at my company are wanting this. :)

**Comment by zambien** [comment]
See #27.  Had to revert since this breaks the tests.  It appears that the create resource does not work:

```
=== RUN   TestAccSharedFlowDeployment_Updated
u: &url.URL{Scheme:"https", Opaque:"", User:(*url.Userinfo)(nil), Host:"api.enterprise.apigee.com", Path:"/v1/o/zambien1977-trial/environments/test/sharedflows/helloFlow/revisions/1/deployments", RawPath:"", ForceQuery:false, RawQuery:"delay=0&override=false", Fragment:""}
--- FAIL: TestAccSharedFlowDeployment_Updated (0.14s)
    testing.go:538: Step 0 error: Error applying: 1 error(s) occurred:
        
        * apigee_shared_flow_deployment.helloFlow_deployment: 1 error(s) occurred:
        
        * apigee_shared_flow_deployment.helloFlow_deployment: [ERROR] resourceSharedFlowDeploymentCreate error deploying: POST https://api.enterprise.apigee.com/v1/o/zambien1977-trial/environments/test/sharedflows/helloFlow/revisions/1/deployments?delay=0&override=false: 404 APIProxy named helloFlow does not exist in organization zambien1977-trial
    testing.go:599: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.
        
        Error: Check failed: Shared flow still exists
        
        State: <no state>

```

Note, you may create a trial account at Apigee to test with.  That is what I've done to test.  Details of how to run the tests are in the readme.md.

**Comment by CodingKayla** [comment]
hmm i tested against our apigee, tho with values for our setup. I'll see if I can reproduce this.

**Comment by CodingKayla** [comment]
@zambien oh we also need https://github.com/zambien/go-apigee-edge/pull/9 merged in for this to fully work

**Comment by zambien** [comment]
@CodingKayla I did pull that into my workspace but forgot to merge.  I still see the issue that I had added above.   I was able to work around it by making the following changes to the test file in question:

```
const testAccCheckSharedFlowDeploymentConfigRequired = `
resource "apigee_shared_flow" "helloFlow" {
   name  = "helloFlow"
   bundle       = "test-fixtures/helloFlow_sharedFlow.zip"
   bundle_sha   = "${base64sha256(file("test-fixtures/helloFlow_sharedFlow.zip"))}"
}

resource "apigee_shared_flow_deployment" "helloFlow_deployment" {
   depends_on = ["apigee_shared_flow.helloFlow"]
   shared_flow_name   = "${apigee_shared_flow.helloFlow.name}"
   org          = "zambien-trial"
   env          = "test"
   revision     = "1"
}
`

const testAccCheckSharedFlowDeploymentConfigUpdated = `
resource "apigee_shared_flow" "helloFlow" {
   name  = "helloFlow"
   bundle       = "test-fixtures/helloFlow_sharedFlow.zip"
   bundle_sha   = "${base64sha256(file("test-fixtures/helloFlow_sharedFlow.zip"))}"
}

resource "apigee_shared_flow_deployment" "helloFlow_deployment" {
   depends_on = ["apigee_shared_flow.helloFlow"]
   shared_flow_name   = "${apigee_shared_flow.helloFlow.name}"
   org          = "zambien-trial"
   env          = "test"
   revision     = "1"
   delay		= "2"
   override 	= true
}
`
```

The reason the test above was failing was that the shared flow didn't exist for the shared flow deployment.  So really, just an issue in the test, not in the actual implementation.

Would you like to include the change above and re-PR?

**Comment by CodingKayla** [comment]
@zambien absolutely, I'll get one in later this evening

**Comment by zambien** [comment]
@CodingKayla cool, sounds good.  Thanks!

**Pull request merged**
